HashTable
isomethane/hse-java-2019 pull request #1
Opened 2019-01-21 04:27 UTC by isomethane

2019-01-27 16:50 UTC, jzuken requested changes

2019-01-27 16:50 UTC, jzuken commented on hashtable/src/main/java/ru/hse/mnmalysheva/hashtable/HashTable.java
> +        return Math.abs(key.hashCode() % table.length);
hashCode() может вернуть отрицательное значение

2019-01-27 16:50 UTC, jzuken commented on hashtable/src/main/java/ru/hse/mnmalysheva/hashtable/HashTable.java
> +    /** Throw exception if key is null. */
бросаемые исключения неплохо бы документировать тоже

2019-01-27 16:50 UTC, jzuken commented on hashtable/src/main/java/ru/hse/mnmalysheva/hashtable/HashTable.java
> +        var removed = (Pair)table[getHash(key)].remove(key);
после `(Pair)` бы пробел поставить ещё

2019-01-28 11:53 UTC, isomethane commented on hashtable/src/main/java/ru/hse/mnmalysheva/hashtable/HashTable.java
> +        return Math.abs(key.hashCode() % table.length);
Я беру модуль

2019-02-11 15:16 UTC, jzuken commented on hashtable/src/main/java/ru/hse/mnmalysheva/hashtable/List.java
> +        private Object data;
эмм, а чего оно Object'ы хранит? вообще в задаче просили только со строками работать, но если вы зачем-то хотите обобщённый список сделать, то лучше сразу делать правильно

2019-03-07 11:37 UTC, merged