Cannon
isomethane/hse-java-2019 pull request #11
Opened 2019-05-22 06:18 UTC by isomethane

2019-05-30 09:53 UTC, RamSaw requested changes
@isomethane В целом все ок, маленькие замечания только.
А вам говорили тесты можно не писать? Если не говорили, то давайте напишем пару тестов на игровой движок игру, заодно проверим насколько данная архитектура тестируема.

2019-05-30 09:53 UTC, RamSaw commented on cannon/build.gradle
> +mainClassName = 'ru.hse.mnmalysheva.cannon.GameUI'
> java -jar ./build/libs/cannon-1.0-SNAPSHOT.jar
> no main manifest attribute, in ./build/libs/cannon-1.0-SNAPSHOT.jar

не удается запустить jar.

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/GameUI.java
> +        landscapeY[1] = Game.HEIGHT;
выделите код с добавлением крайних точек в метод, название которого бы говоорила, зачем мы это делаем, ну или джавадок к нему. А то сходу кажется непонятно, зачем мы их добавляем, как я понял мы это делаем для создания прямоугольника и потом его заливки.

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/GameUI.java
> +        landscapeY[1] = Game.HEIGHT;
типа getPolygonToFillByLandscapePoints

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/GameUI.java
> +                double deltaTime = (now - previousTime) * 1e-9;
1e-9 = convertToSeconds?

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/GameUI.java
> +    private class Explosion {
Давайте может его вынесим в отдельный файл, а то и так много кода и непонятно чем Explosion сильно отличается от cannon и других сущностей.

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/Cannon.java
> +    /** Updates projectile state with respect to time since last update. **/
projectile? мб cannon?

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/Game.java
> +    public @NotNull Target getTarget() {
not used

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/Game.java
> +        IN_PROGRESS, WIN, LOSE
LOSE not used

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/GameUI.java
> +    public void start(@NotNull Stage primaryStage) {
метод довольно большой, но хорошо бьется на логические части, давайте разобьем, так и легче будет понимать, что делает какждая из частей.

2019-05-30 09:53 UTC, RamSaw commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/Projectile.java
> +    private static final double GRAVITY_ACCELERATION = 350;
а где же 9.8? :)

2019-06-06 20:19 UTC, isomethane commented on cannon/src/main/java/ru/hse/mnmalysheva/cannon/Projectile.java
> +    private static final double GRAVITY_ACCELERATION = 350;
Действие происходит не на Земле

2019-06-06 20:19 UTC, isomethane commented
@RamSaw пофиксила

2019-06-07 17:01 UTC, RamSaw approved these changes
@isomethane все ок
@jzuken

2019-06-08 08:12 UTC, merged