ThreadPool
isomethane/hse-java-2019 pull request #9
Opened 2019-05-01 04:53 UTC by isomethane

2019-05-04 21:32 UTC, RamSaw requested changes
@isomethane домашку проверил.

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/LightFuture.java
> +    <R> LightFuture<R> thenApply(Function<T, R> function);
Наиболее общий тип?
-0.5

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +     * @throws InterruptedException if current thread was interrupted while waiting.
а должен ли? 
в джава если не все потоки завершатся, то программа никогда не завершится.
кажется, что если мы приняли interrupted exception в данном случае лучше его проигнорировать и дозавершить все потоки.

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +            synchronized (queue) {
а это вынесено сознательно и не сделан synchronized метод? для производительности?

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +        private T get() throws InterruptedException {
а как же spurious wakeups. Надо ловить его и проверять, что мы из isFinished.

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +                        readinessLock.wait();
spurious wakeup

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +        var expected = IntStream.range(0, numberOfTasks).boxed().collect(Collectors.toList());
разве порядок чисел гарантируется? наверное set лучше

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +    @RepeatedTest(REPEATED_TEST_COUNT)
крутая штука. еще JCStress есть.

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +        future.get();
assert

2019-05-04 21:32 UTC, RamSaw commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +            future.get();
assert на них тоже бы. мы же знаем, что должно тоже самое вернуться.

2019-05-19 20:12 UTC, isomethane commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +        private T get() throws InterruptedException {
Не очень поняла, о чем речь. Кажется, spurious interrupt-ов не бывает.

2019-05-19 20:12 UTC, isomethane commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +                        readinessLock.wait();
Да, а что не так?

2019-05-19 20:17 UTC, isomethane commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +        var expected = IntStream.range(0, numberOfTasks).boxed().collect(Collectors.toList());
В этом тесте пул из одного потока. Мне хочется, чтобы таски лежали именно в очереди, потому что, например, если там будет стек, то какие-то из них могут ждать своей очереди бесконечно долго.

2019-05-19 20:17 UTC, isomethane commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +    @RepeatedTest(REPEATED_TEST_COUNT)
Спасибо

2019-05-19 20:21 UTC, isomethane commented
@RawSaw исправила все, кроме непонятного момента со spurious wakeups.

2019-05-22 13:05 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +            while (!isSuccessful) {
у join кстати не должно быть spurious wakeups, так как внутри него loop с wait реализован ( https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#join(long) )
так что видимо этот код излишний.

2019-05-22 13:05 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +        private T get() throws InterruptedException {
Да, Вы конечно правы, я тут что-то странное написал. То что throws InterruptedException это правильно.

2019-05-22 13:11 UTC, RamSaw requested changes
@isomethane давайте join обсудим и все ок будет.

2019-05-22 13:11 UTC, RamSaw commented on threadpool/src/test/java/ru/hse/mnmalysheva/ThreadPoolTest.java
> +        var expected = IntStream.range(0, numberOfTasks).boxed().collect(Collectors.toList());
А, да. Крутой тест тогда :+1:

2019-05-22 14:24 UTC, isomethane commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +            while (!isSuccessful) {
Согласна, что этот код не очень, но он не про spurious wakeups. Поток, в котором он выполняется, действительно могли прервать, и в таком случае лучше это проигнорировать и дозавершить потоки (пересказ Вашего комментария, который я считаю совершенно справедливым).
Метод shutdown заявлен как ожидающий потоки, поэтому, наверное, было бы странно, если бы он в каких-то случаях завершался успешно, но при этом не дожидался завешения потоков. Поэтому не вижу других вариантов, кроме как ждать в цикле.
interrupt на каждом шаге цикла я делаю потому, что это повышает шансы потока завершиться в случае, если InterruptedException будет пойман внутри таска (хотя при таком поведении все равно никаких гарантий быть не может).

2019-05-22 14:27 UTC, isomethane commented
@RamSaw написала свои мысли про join.

2019-05-22 14:29 UTC, RamSaw approved these changes
@jzuken проверил.

2019-05-22 14:29 UTC, RamSaw commented on threadpool/src/main/java/ru/hse/mnmalysheva/ThreadPool.java
> +            while (!isSuccessful) {
окей, логично

2019-06-06 07:22 UTC, jzuken commented on threadpool/src/main/java/ru/hse/mnmalysheva/LightExecutionException.java
> +/** Exception thrown when trying to get the result of a task that executed with an exception. **/
это официально самая подробная документация на класс исключения, что я видел

2019-06-06 07:22 UTC, merged